//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMessenger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string group_admin_pass { get; set; }
        public string group_user_pass { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
    }
}
